export VERSION := 1.5.0

YYPKG_FILES := http://win-builds.org/yypkg
YYPKG_VERSION := 1.9.0

COREUTILS_VERSION := 8.21
MAKE_VERSION := 4.1
SED_VERSION := 4.2.2
FINDUTILS_VERSION := 4.4.2
OCAML_VERSION := 4.02.1
FINDLIB_VERSION := 1.5.5

FILEUTILS_VERSION := 0.4.5
ARCHIVE_VERSION := 2.8.4+2
CRYPTOKIT_VERSION := 1.9
LIBOCAML_VERSION := v2014-08-08

WEB := notk.org:/var/www/win-builds.org

export MIRROR := http://win-builds.org/$(VERSION)/tarballs

-include Makefile.data.local
