export VERSION := 1.5-rc2

YYPKG_FILES := http://win-builds.org/yypkg
YYPKG_VERSION := 1.9-rc7

FILEUTILS_VERSION := 0.4.5
ARCHIVE_VERSION := 2.8.4+2
CRYPTOKIT_VERSION := 1.9
LIBOCAML_VERSION := v2014-08-08
EFL_VERSION := 1.11.1

WEB := notk.org:/var/www/win-builds.org

export MIRROR := http://win-builds.org/$(VERSION)/tarballs
