#!/bin/sh

set -eux

slackbuild=$1
folder=$(dirname $slackbuild)

cd $folder

################################################################################
### Settings ###
################################################################################

if [ "$TRIPLET" = "i686-w64-mingw32" ]; then
  LIBDIRSUFFIX=""
  EXE_FORMAT="PE"
  STRIP=${TRIPLET}-strip
elif [ "$TRIPLET" = "x86_64-w64-mingw32" ]; then
  LIBDIRSUFFIX="64"
  EXE_FORMAT="PE"
  STRIP=${TRIPLET}-strip
fi

LIBDIR="${YYPREFIX}/lib${LIBDIRSUFFIX}"
export PKG_CONFIG_LIBDIR=${LIBDIR}}/pkgconfig
export PKG_CONFIG_PATH=""
export LD_LIBRARY_PATH=${LIBDIR}
export EXE_FORMAT
export STRIP

################################################################################
### Fire up the slackbuild ###
################################################################################

HST="${HST}" TGT=${TGT} PREFIX=${PREFIX} ./${slackbuild}

